#Target_name : Dependencies
#<TAB>Command

 CC = gcc

linux : main.c ./src/atm_operation.c ./inc/atm_operation.h
	$(CC) main.c ./src/atm_operation.c ./inc/atm_operation.h -o all.out

target : main.c ./src/atm_operation.c ./inc/atm_operation.h
	$(CC) main.c ./src/atm_operation.c ./inc/atm_operation.h -o output


clean:
	rm *o output  rm *o out


